export const IMAGES = {
  SS: {
    start1: require('../assets/images/start_1.jpg'),
    start2: require('../assets/images/start_2.jpg'),
    start3: require('../assets/images/start_3.jpg'),
    account1: require('../assets/images/account_1.jpg'),
    account2: require('../assets/images/account_2.jpg'),
    account3: require('../assets/images/account_3.jpg'),
    playPractice1: require('../assets/images/play_p_1.jpg'),
    playPractice2: require('../assets/images/play_p_2.jpg'),
    playPractice3: require('../assets/images/play_p_3.jpg'),
    playPractice4: require('../assets/images/play_p_4.jpg'),
    playPractice5: require('../assets/images/play_p_5.jpg'),
    playPractice6: require('../assets/images/play_p_6.jpg'),
    playCompetition1: require('../assets/images/play_c_1.jpg'),
    playCompetition2: require('../assets/images/play_c_2.jpg'),
    playCompetition3: require('../assets/images/play_c_3.jpg'),
    playCompetition4: require('../assets/images/play_c_4.jpg'),
    playCompetition5: require('../assets/images/play_c_5.jpg'),
    playCompetition6: require('../assets/images/play_c_6.jpg'),
  },
  MODES: {
    practice: require('../assets/images/icons/practice.svg'),
    competition: require('../assets/images/icons/competition.svg'),
  },
  GAMES: {
    brightness: require('../assets/images/games/brightness.png'),
    colorCode1: require('../assets/images/games/color_code1.png'),
    colorCode2: require('../assets/images/games/color_code2.png'),
    differentFont: require('../assets/images/games/different_font.png'),
    gradient: require('../assets/images/games/gradient.png'),
    majorityCase: require('../assets/images/games/majority_case.png'),
    majorityShape: require('../assets/images/games/majority_shape.png'),
    rectangle: require('../assets/images/games/rectangle.png'),
    sameColor: require('../assets/images/games/same_color.png'),
    typeface: require('../assets/images/games/typeface.png'),
  },
};
